stages:
  - build

build-and-push:
  stage: build
  services:
    - name: docker:20.10.16-dind
      alias: docker
  variables:
    BUN_INSTALL_CACHE_DIR: .bun/install/cache
    DOCKER_HOST: tcp://docker:2375
    DOCKER_TLS_CERTDIR: ""

  cache:
    key:
      files:
        - bun.lock
    paths:
      - .bun/install/cache/
      - node_modules/

  before_script:
    - apt-get update
    - apt-get install -y ca-certificates curl
    - curl -fsSL https://download.docker.com/linux/static/stable/x86_64/docker-latest.tgz | tar -xz -C /usr/local/bin --strip-components=1 docker/docker
    - bun install --frozen-lockfile
    - bun run compile linux-x64-baseline --no-version-tag
    - echo "$CI_REGISTRY_PASSWORD" | docker login $CI_REGISTRY -u $CI_REGISTRY_USER --password-stdin

  script:
    - docker build -f docker/Dockerfile -t "$CI_REGISTRY_IMAGE:latest" .
    - docker push "$CI_REGISTRY_IMAGE:latest"
